export const ALL_COACH_LOAD_REQUEST = "ALL_COACH_LOAD_REQUEST";
export const ALL_COACH_LOAD_SUCCESS = "ALL_COACH_LOAD_SUCCESS";
export const ALL_COACH_LOAD_FAIL = "ALL_COACH_LOAD_FAIL";
export const ALL_COACH_LOAD_RESET = "ALL_COACH_LOAD_RESET";

export const COACH_DELETE_REQUEST = "COACH_DELETE_REQUEST";
export const COACH_DELETE_SUCCESS = "COACH_DELETE_SUCCESS";
export const COACH_DELETE_FAIL = "COACH_DELETE_FAIL";
export const COACH_DELETE_RESET = "COACH_DELETE_RESET";

export const COACH_UPDATE_REQUEST = "COACH_UPDATE_REQUEST";
export const COACH_UPDATE_SUCCESS = "COACH_UPDATE_SUCCESS";
export const COACH_UPDATE_FAIL = "COACH_UPDATE_FAIL";
export const COACH_UPDATE_RESET = "COACH_UPDATE_RESET";

export const SINGLE_COACH_LOAD_REQUEST = "SINGLE_COACH_LOAD_REQUEST";
export const SINGLE_COACH_LOAD_SUCCESS = "SINGLE_COACH_LOAD_SUCCESS";
export const SINGLE_COACH_LOAD_FAIL = "SINGLE_COACH_LOAD_FAIL";
export const SINGLE_COACH_LOAD_RESET = "SINGLE_COACH_LOAD_RESET";

export const COACH_CREATE_FAIL = "COACH_CREATE_FAIL"
export const COACH_CREATE_REQUEST = "COACH_CREATE_REQUEST"
export const COACH_CREATE_RESET = "COACH_CREATE_RESET"
export const COACH_CREATE_SUCCESS = "COACH_CREATE_SUCCESS"