export const EVENT_LOAD_REQUEST = "EVENT_LOAD_REQUEST";
export const EVENT_LOAD_SUCCESS = "EVENT_LOAD_SUCCESS";
export const EVENT_LOAD_FAIL = "EVENT_LOAD_FAIL";
export const EVENT_LOAD_RESET = "EVENT_LOAD_RESET";

export const EVENT_LOAD_SINGLE_REQUEST = "EVENT_LOAD_SINGLE_REQUEST";
export const EVENT_LOAD_SINGLE_SUCCESS = "EVENT_LOAD_SINGLE_SUCCESS";
export const EVENT_LOAD_SINGLE_FAIL = "EVENT_LOAD_SINGLE_FAIL";
export const EVENT_LOAD_SINGLE_RESET = "EVENT_LOAD_SINGLE_RESET";

export const REGISTER_EVENT_REQUEST = "REGISTER_EVENT_REQUEST";
export const REGISTER_EVENT_SUCCESS = "REGISTER_EVENT_SUCCESS";
export const REGISTER_EVENT_FAIL = "REGISTER_EVENT_FAIL";
export const REGISTER_EVENT_RESET = "REGISTER_EVENT_RESET";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";


export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";
export const EDIT_EVENT_RESET = "EDIT_EVENT_RESET";