export const EVENT_TYPE_LOAD_REQUEST = "EVENT_TYPE_LOAD_REQUEST";
export const EVENT_TYPE_LOAD_SUCCESS = "EVENT_TYPE_LOAD_SUCCESS";
export const EVENT_TYPE_LOAD_FAIL = "EVENT_TYPE_LOAD_FAIL";
export const EVENT_TYPE_LOAD_RESET = "EVENT_TYPE_LOAD_RESET";

export const CREATE_EVENT_TYPE_REQUEST = "CREATE_EVENT_TYPE_REQUEST";
export const CREATE_EVENT_TYPE_SUCCESS = "CREATE_EVENT_TYPE_SUCCESS";
export const CREATE_EVENT_TYPE_FAIL = "CREATE_EVENT_TYPE_FAIL";
export const CREATE_EVENT_TYPE_RESET = "CREATE_EVENT_TYPE_RESET";

export const DELETE_EVENT_TYPE_REQUEST = "DELETE_EVENT_TYPE_REQUEST";
export const DELETE_EVENT_TYPE_SUCCESS= "DELETE_EVENT_TYPE_SUCCESS";
export const DELETE_EVENT_TYPE_FAIL = "DELETE_EVENT_TYPE_FAIL";
export const DELETE_EVENT_TYPE_RESET = "DELETE_EVENT_TYPE_RESET";