export const PSESSION_LOAD_REQUEST = "PSESSION_LOAD_REQUEST";
export const PSESSION_LOAD_SUCCESS = "PSESSION_LOAD_SUCCESS"; 
export const PSESSION_LOAD_FAIL = "PSESSION_LOAD_FAIL";
export const PSESSION_LOAD_RESET = "PSESSION_LOAD_RESET";

//single job load

export const PSESSION_SINGLE_LOAD_REQUEST = "PSESSION_LOAD_REQUEST";
export const PSESSION_SINGLE_LOAD_SUCCESS = "PSESSION_LOAD_SUCCESS"; 
export const PSESSION_SINGLE_LOAD_FAIL = "PSESSION_LOAD_FAIL";
export const PSESSION_SINGLE_LOAD_RESET = "PSESSION_LOAD_RESET";


//jobType

export const PSESSION_TYPE_LOAD_REQUEST = "PSESSION_TYPE_LOAD_REQUEST";
export const PSESSION_TYPE_LOAD_SUCCESS = "PSESSION_TYPE_LOAD_SUCCESS";
export const PSESSION_TYPE_LOAD_FAIL = "PSESSION_TYPE_LOAD_FAIL";
export const PSESSION_TYPE_LOAD_RESET = "PSESSION_TYPE_LOAD_RESET";

//Register practice session

export const REGISTER_PSESSION_REQUEST = "REGISTER_PSESSION_REQUEST";
export const REGISTER_PSESSION_SUCCESS = "REGISTER_PSESSION_SUCCESS";
export const REGISTER_PSESSION_FAIL = "REGISTER_PSESSION_FAIL";
export const REGISTER_PSESSION_RESET = "REGISTER_PSESSION_RESET";

//Delete practice session

export const DELETE_PSESSION_REQUEST = "DELETE_PSESSION_REQUEST";
export const DELETE_PSESSION_SUCCESS = "DELETE_PSESSION_SUCCESS";
export const DELETE_PSESSION_FAIL = "DELETE_PSESSION_FAIL";
export const DELETE_PSESSION_RESET = "DELETE_PSESSION_RESET";

//Update practice session

export const UPDATE_PSESSION_REQUEST = "UPDATE_PSESSION_REQUEST"
export const UPDATE_PSESSION_SUCCESS = "UPDATE_PSESSION_SUCCESS"
export const UPDATE_PSESSION_FAIL = "UPDATE_PSESSION_FAIL"
export const UPDATE_PSESSION_RESET = "UPDATE_PSESSION_RESET"